name: Pipeline Cloudfunc
on:
  push:
    branches:
      - main
jobs:
  entry-point:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - run: >
          npm install -g npm-cli-login
          yarn install
      - run: yarn test
      - run: >
          echo "ACTUAL_VERSION=$(node -e "console.log(require('./package.json').version);")" >> $GITHUB_ENV
          echo "Version to publish: ${{env.ACTUAL_VERSION}}"
      - name: Login
        run: npm-cli-login -u ${{env.USERNAME}} -p ${{env.PASSWORD}} -e ${{env.EMAIL}}
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
      - run: |
          yarn publish --new-version ${{env.ACTUAL_VERSION}} --access public