name: Pipeline Cloudfunc
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.version_step.outputs.version}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - id: version_step
        run: echo "::set-output name=version::$(node -e "console.log(require('./package.json').version);")"
      - uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: './dist/'
          retention-days: 1
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: './package.json'
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    environment: 'package'
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: distribution
          path: './dist/'
      - uses: actions/download-artifact@v2
        with:
          name: package
          path: './package.json'
      - run: >
          npm install -g npm-cli-login
      - run: >
          echo "Version to publish: ${{needs.build.outputs.version}}"
      - name: Login
        run: npm-cli-login -u ${{env.USERNAME}} -p ${{env.PASSWORD}} -e ${{env.EMAIL}}
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
      - run: |
          yarn publish --new-version ${{needs.build.outputs.version}} --access public
